import { describe, expect, it } from 'vitest';
import fixture from './__fixtures__/colorResolutionRealCatalog.json';
import { resolveMaterialName } from './colors';
import type { Material } from '../api/types';

/**
 * Cross-validation between the TypeScript port of resolve_material_name
 * (colors.ts) and the backend original (app/services/material_naming.py) —
 * see ADR-0031 п.4/п.5 "Отклонено" (duplicating the resolution logic across
 * backend/frontend) and docs/known-issues.md.
 *
 * This does NOT remove the duplication — ADR-0031 explicitly rejected a
 * network round-trip to the backend just to resolve a name for display. It
 * exists so a future change to the backend's color-parsing format (a new
 * color, a new writing pattern) that isn't mirrored in colors.ts fails a
 * test instead of silently producing wrong supplier-facing text.
 *
 * fixture is generated by backend/app/scripts/generate_color_resolution_fixture.py
 * from the real price-matrix xlsx (the same 147-material set ADR-0031 Step 0
 * found) — it is NOT re-derived at test time. Re-run that script (and
 * re-commit the resulting JSON) whenever backend/app/services/material_naming.py
 * changes; this test failing without a script re-run is the signal that a
 * drift needs investigating, not something to silence by regenerating blindly.
 */

interface FixtureRow {
  internal_sku: string;
  canonical_name: string;
  color_options: string[];
  color_fragment: string;
  resolved: Record<string, string>;
}

interface Fixture {
  colors_tested: string[];
  materials: FixtureRow[];
}

const { colors_tested: colorsTested, materials: fixtureMaterials } = fixture as Fixture;

describe('resolveMaterialName cross-validation against backend (real catalog, ADR-0031)', () => {
  it('fixture actually contains the real catalog\'s full 147-material color set, not an empty/stale file', () => {
    expect(fixtureMaterials.length).toBe(147);
    expect(colorsTested.sort()).toEqual(['Bronze', 'White']);
  });

  it.each(fixtureMaterials.flatMap((row) => colorsTested.map((color) => ({ row, color }))))(
    'matches backend resolve_material_name for $row.internal_sku / $color',
    ({ row, color }: { row: FixtureRow; color: string }) => {
      const material: Material = {
        id: row.internal_sku,
        internal_sku: row.internal_sku,
        canonical_name: row.canonical_name,
        category: null,
        unit: 'pcs',
        attributes: {},
        color_options: row.color_options,
        color_fragment: row.color_fragment,
      };

      const tsResult = resolveMaterialName(material, color);
      const backendResult = row.resolved[color];

      expect(tsResult).toBe(backendResult);
    },
  );
});
